name: "Build Armbian for OrangePi 5 Plus"
on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Download Armbian Soure
        run: |
          git clone --depth 1 --branch v25.05 https://github.com/armbian/build

      - name: Build Armbian
        run: |
          cd build;
          ./compile.sh build BOARD=orangepi5-plus BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=bookworm

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/output/images/*
