name: "Build Armbian for OrangePi 5 Plus"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "Release tag (e.g. v1.0.0)"
        required: true

jobs:
  build-armbian:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Download Armbian Soure
        run: |
          git clone --depth 1 --branch v25.05 https://github.com/armbian/build

      - name: Build Armbian
        id: build
        run: |
          cd build;
          ./compile.sh build BOARD=orangepi5-plus BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=bookworm PREFER_DOCKER=no;
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Generate Release log
        run: |
          touch release.md
          echo "## ${{ github.workflow }}" >> release.md       

      - name: Release
        uses: softprops/action-gh-release@master
        if: steps.build.outputs.status == 'success' && !cancelled()
        with:
          tag_name: ${{ github.event.inputs.tag }}
          body_path: release.md
          files: |
            build/output/images/*
            
